# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groupCheckBoxes.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(868, 664)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(400, 20, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBoxIceCreams = QtWidgets.QGroupBox(Dialog)
        self.groupBoxIceCreams.setGeometry(QtCore.QRect(330, 110, 271, 221))
        self.groupBoxIceCreams.setCheckable(True)
        self.groupBoxIceCreams.setObjectName("groupBoxIceCreams")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBoxIceCreams)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 211, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxMintChocolate = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxMintChocolate.setObjectName("checkBoxMintChocolate")
        self.verticalLayout.addWidget(self.checkBoxMintChocolate)
        self.checkBoxCookieDough = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxCookieDough.setObjectName("checkBoxCookieDough")
        self.verticalLayout.addWidget(self.checkBoxCookieDough)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBoxIceCreams)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 120, 211, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBoxChocolateAlmond = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxChocolateAlmond.setObjectName("checkBoxChocolateAlmond")
        self.verticalLayout_3.addWidget(self.checkBoxChocolateAlmond)
        self.checkBoxRockyRoad = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxRockyRoad.setObjectName("checkBoxRockyRoad")
        self.verticalLayout_3.addWidget(self.checkBoxRockyRoad)
        self.groupBoxDrinks = QtWidgets.QGroupBox(Dialog)
        self.groupBoxDrinks.setGeometry(QtCore.QRect(330, 350, 271, 161))
        self.groupBoxDrinks.setCheckable(True)
        self.groupBoxDrinks.setObjectName("groupBoxDrinks")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxDrinks)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 160, 83))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxCoffee = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxCoffee.setObjectName("checkBoxCoffee")
        self.verticalLayout_2.addWidget(self.checkBoxCoffee)
        self.checkBoxSoda = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxSoda.setObjectName("checkBoxSoda")
        self.verticalLayout_2.addWidget(self.checkBoxSoda)
        self.checkBoxTea = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxTea.setObjectName("checkBoxTea")
        self.verticalLayout_2.addWidget(self.checkBoxTea)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 340, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.priceTextLabel = QtWidgets.QLabel(Dialog)
        self.priceTextLabel.setGeometry(QtCore.QRect(90, 560, 661, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.priceTextLabel.setFont(font)
        self.priceTextLabel.setText("")
        self.priceTextLabel.setObjectName("priceTextLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Menu"))
        self.label_2.setText(_translate("Dialog", "Select your IceCream"))
        self.groupBoxIceCreams.setTitle(_translate("Dialog", "IceCreams"))
        self.checkBoxMintChocolate.setText(_translate("Dialog", "Mint Chocolate Chips $4"))
        self.checkBoxCookieDough.setText(_translate("Dialog", "Cookie Dough $2"))
        self.checkBoxChocolateAlmond.setText(_translate("Dialog", "Chocolate Almond $3"))
        self.checkBoxRockyRoad.setText(_translate("Dialog", "Rocky Road $5"))
        self.groupBoxDrinks.setTitle(_translate("Dialog", "Drinks"))
        self.checkBoxCoffee.setText(_translate("Dialog", "Coffee $2"))
        self.checkBoxSoda.setText(_translate("Dialog", "Soda $3"))
        self.checkBoxTea.setText(_translate("Dialog", "Tea $1"))
        self.label_3.setText(_translate("Dialog", "Select your drink"))

